version: '3.0'
services:
    Java:
        build: /var/lib/jenkins/workspace/ABC
        container_name: uathcmajna
        image: uat_hcm_ajna
        networks:
            - java_connect
        ports:
            - 9090:9090
        restart: always 
        environment:
           - DB_USERNAME=${DB_USERNAME}
           - DB_PASSWORD=${DB_PASSWORD}
networks:
    java_connect:
        external: true
