version: '3.0'
services:
    Java:
        build: /var/lib/jenkins/workspace/ABC
        container_name: uathcmajna
        image: uat_hcm_ajna
        networks:
            - java_connect
        ports:
            - 9090:9090
        restart: always 
        environment:
           - DB_USERNAME=$DB_CREDENTIALS_USR
           - DB_PASSWORD=$DB_CREDENTIALS_PSW
           - DB_URL=$DB_URL
networks:
    java_connect:
        external: true
