version: '3.0'
services:
    Java:
        build: /root/jenkins/workspace/uat_hcm_ajna
        container_name: uathcmajna
        image: uat_hcm_ajna
        networks:
            - java_connect
        ports:
            - 5001:5001
        restart: always          
networks:
    java_connect:
        external: true
