version: '3.0'
services:
    Java:
        build: /var/lib/jenkins/workspace/update_spring_boot_application@tmp
        container_name: uathcmajna
        image: uat_hcm_ajna
        networks:
            - java_connect
        ports:
            - 9090:9090
        restart: always          
networks:
    java_connect:
        external: true
