version: '3.0'
services:
    Java:
        build: /var/lib/jenkins/workspace/uat_hcm_ajna_uat
        container_name: uathcmajna_uat
        image: uat_hcm_ajna_uat
        networks:
            - java_connect
        ports:
            - 5001:5001
        restart: always 
        environment:
           - DB_USERNAME=${DB_USERNAME}
           - DB_PASSWORD=${DB_PASSWORD}
           - DB_URL=${DB_URL}
networks:
    java_connect:
        external: true
