package com.omfysgroup.ajanhcm.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LeaveSetting implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.time.LocalDate lsd;
	private long priorDays;
	private java.lang.String message;

	private java.time.LocalDate led;

	private long afterDays;

	private boolean pwflag;

	private boolean swflag;

	private boolean ma;

	private long nlforma;

	private boolean lcAllowed;

	private java.time.LocalDate applicableFrom;

	private java.time.LocalDate applicableToDate;

	private long nOfLforMA;

	private java.lang.String leaveType;

	private long leaveCount;

	public LeaveSetting() {
	}

	public java.time.LocalDate getLsd() {
		return this.lsd;
	}

	public void setLsd(java.time.LocalDate lsd) {
		this.lsd = lsd;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public long getPriorDays() {
		return this.priorDays;
	}

	public void setPriorDays(long priorDays) {
		this.priorDays = priorDays;
	}

	public java.time.LocalDate getLed() {
		return this.led;
	}

	public void setLed(java.time.LocalDate led) {
		this.led = led;
	}

	public long getAfterDays() {
		return this.afterDays;
	}

	public void setAfterDays(long afterDays) {
		this.afterDays = afterDays;
	}

	public boolean isPwflag() {
		return this.pwflag;
	}

	public void setPwflag(boolean pwflag) {
		this.pwflag = pwflag;
	}

	public boolean isSwflag() {
		return this.swflag;
	}

	public void setSwflag(boolean swflag) {
		this.swflag = swflag;
	}

	public boolean isMa() {
		return this.ma;
	}

	public void setMa(boolean ma) {
		this.ma = ma;
	}

	public long getNlforma() {
		return this.nlforma;
	}

	public void setNlforma(long nlforma) {
		this.nlforma = nlforma;
	}

	public boolean isLcAllowed() {
		return this.lcAllowed;
	}

	public void setLcAllowed(boolean lcAllowed) {
		this.lcAllowed = lcAllowed;
	}

	public java.time.LocalDate getApplicableFrom() {
		return this.applicableFrom;
	}

	public void setApplicableFrom(java.time.LocalDate applicableFrom) {
		this.applicableFrom = applicableFrom;
	}

	public java.time.LocalDate getApplicableToDate() {
		return this.applicableToDate;
	}

	public void setApplicableToDate(java.time.LocalDate applicableToDate) {
		this.applicableToDate = applicableToDate;
	}

	public long getnOfLforMA() {
		return this.nOfLforMA;
	}

	public void setnOfLforMA(long nOfLforMA) {
		this.nOfLforMA = nOfLforMA;
	}

	public java.lang.String getLeaveType() {
		return this.leaveType;
	}

	public void setLeaveType(java.lang.String leaveType) {
		this.leaveType = leaveType;
	}

	public long getLeaveCount() {
		return this.leaveCount;
	}

	public void setLeaveCount(long leaveCount) {
		this.leaveCount = leaveCount;
	}

	public LeaveSetting(java.time.LocalDate lsd, long priorDays,
			java.lang.String message, java.time.LocalDate led, long afterDays,
			boolean pwflag, boolean swflag, boolean ma, long nlforma,
			boolean lcAllowed, java.time.LocalDate applicableFrom,
			java.time.LocalDate applicableToDate, long nOfLforMA,
			java.lang.String leaveType, long leaveCount) {
		this.lsd = lsd;
		this.priorDays = priorDays;
		this.message = message;
		this.led = led;
		this.afterDays = afterDays;
		this.pwflag = pwflag;
		this.swflag = swflag;
		this.ma = ma;
		this.nlforma = nlforma;
		this.lcAllowed = lcAllowed;
		this.applicableFrom = applicableFrom;
		this.applicableToDate = applicableToDate;
		this.nOfLforMA = nOfLforMA;
		this.leaveType = leaveType;
		this.leaveCount = leaveCount;
	}

}